# Generated by Django 3.0.2 on 2020-01-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=50)),
                ('project_start', models.DateField()),
                ('project_finish', models.DateField()),
            ],
        ),
    ]
