# Generated by Django 3.0.2 on 2020-01-27 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200127_0044'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_project_id',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_concluded',
            field=models.BooleanField(default=False, verbose_name='Atividade Concluida'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_datefinish',
            field=models.DateField(verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_datestart',
            field=models.DateField(verbose_name='Data Inicial'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=50, verbose_name='Nome da Atividade'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='ID do Projeto'),
        ),
    ]
